ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020304.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020304.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020304.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020304_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020318.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020318.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020318.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020318_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020403.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020403.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020403.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020403_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020415.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020415.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020415.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020415_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020430.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020430.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020430.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020430_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020512.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020512.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020512.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020512_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020603.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020603.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020603.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020603_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020617.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020617.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020617.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020617_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020701.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020701.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020701.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020701_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020714.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020714.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020714.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020714_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020801.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020801.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020801.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020801_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020816.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020816.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020816.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020816_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020904.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020904.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020904.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020904_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020918.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020918.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020918.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/020918_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021002.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021002.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021002.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021002_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021016.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021016.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021016.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021016_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021030.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021030.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021030.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021030_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021113.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021113.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021113.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021113_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021128.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021128.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021128.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/021128_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030011.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030011.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030011.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030011_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030025.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030025.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030025.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030025_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030109.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030109.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030109.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030109_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030126.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030126.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030126.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030126_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030209.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030209.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030209.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030209_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030221.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030221.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030221.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030221_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030304.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030304.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030304.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030304_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030318.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030318.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030318.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030318_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030401.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030401.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030401.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030401_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030418.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030418.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030418.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030418_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030501.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030501.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030501.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030501_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030515.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030515.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030515.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030515_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030529.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030529.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030529.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030529_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030609.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030609.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030609.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030609_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030707.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030707.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030707.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030707_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030801.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030801.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030801.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030801_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030814.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030814.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030814.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030814_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030826.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030826.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030826.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030826_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030916.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030916.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030916.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/030916_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031015.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031015.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031015.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031015_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031101.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031101.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031101.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031101_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031114.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031114.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031114.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/031114_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040014.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040014.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040014.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040014_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040115.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040115.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040115.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040115_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040217.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040217.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040217.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040217_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040309.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040309.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040309.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040309_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040401.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040401.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040401.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040401_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040413.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040413.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040413.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040413_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040511.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040511.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040511.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040511_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040624.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040624.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040624.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040624_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040701.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040701.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040701.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040701_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040729.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040729.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040729.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040729_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040902.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040902.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040902.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/040902_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/041002.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/041002.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/041002.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/041002_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/041023.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/041023.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/041023.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/041023_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/050212.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/050212.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/050212.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Adam/050212_ipsyn.txt
