ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010600a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010600a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010600a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010600a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010600b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010600b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010600b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010600b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010700a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010700a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010700a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010700a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010700b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010700b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010700b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010700b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010800.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010800.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010800.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010800_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900c.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900c.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900c.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/010900c_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011000a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011000a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011000a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011000a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011000b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011000b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011000b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011000b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011100a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011100a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011100a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011100a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011100b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011100b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011100b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/011100b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020000a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020000a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020000a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020000a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020000b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020000b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020000b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020000b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020100a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020100a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020100a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020100a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020100b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020100b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020100b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020100b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020200a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020200a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020200a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020200a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020200b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020200b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020200b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020200b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020300a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020300a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020300a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020300a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020300b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020300b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020300b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Eve/020300b_ipsyn.txt
