ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020305.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020305.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020305.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020305_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020307.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020307.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020307.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020307_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020319.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020319.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020319.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020319_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020322.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020322.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020322.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020322_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020326.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020326.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020326.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020326_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020328.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020328.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020328.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020328_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020410.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020410.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020410.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020410_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020412.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020412.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020412.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020412_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020417.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020417.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020417.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020417_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020419.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020419.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020419.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020419_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020426.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020426.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020426.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020426_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020507.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020507.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020507.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020507_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020515.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020515.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020515.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020515_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020525.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020525.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020525.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020525_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020530.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020530.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020530.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020530_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020604.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020604.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020604.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020604_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020613.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020613.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020613.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020613_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020620.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020620.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020620.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020620_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020630.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020630.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020630.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020630_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020705.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020705.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020705.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020705_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020712.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020712.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020712.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020712_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020718.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020718.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020718.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020718_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020728.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020728.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020728.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020728_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020802.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020802.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020802.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020802_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020825a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020825a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020825a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020825a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020825b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020825b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020825b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020825b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020900.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020900.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020900.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020900_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020906.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020906.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020906.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020906_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020914.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020914.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020914.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020914_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020920.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020920.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020920.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020920_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020929.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020929.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020929.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/020929_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021005.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021005.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021005.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021005_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021011.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021011.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021011.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021011_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021020.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021020.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021020.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021020_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021024.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021024.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021024.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021024_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021102.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021102.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021102.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021102_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021117.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021117.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021117.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021117_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021123.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021123.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021123.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021123_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021130.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021130.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021130.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/021130_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030018a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030018a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030018a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030018a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030018b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030018b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030018b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030018b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030027.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030027.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030027.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030027_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030103.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030103.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030103.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030103_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030110.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030110.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030110.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030110_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030117.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030117.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030117.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030117_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030124.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030124.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030124.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030124_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030202.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030202.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030202.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030202_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030210.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030210.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030210.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030210_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030216.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030216.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030216.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030216_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030223.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030223.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030223.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030223_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030307a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030307a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030307a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030307a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030307b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030307b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030307b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030307b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030313.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030313.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030313.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030313_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030320.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030320.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030320.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030320_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030328.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030328.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030328.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030328_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030401.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030401.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030401.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030401_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030409.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030409.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030409.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030409_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030416.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030416.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030416.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030416_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030426.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030426.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030426.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030426_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030501.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030501.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030501.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030501_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030507.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030507.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030507.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030507_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030513.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030513.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030513.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030513_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030520.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030520.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030520.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030520_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030606.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030606.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030606.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030606_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030616.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030616.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030616.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030616_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030623.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030623.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030623.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030623_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030630.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030630.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030630.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030630_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030709.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030709.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030709.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030709_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030716.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030716.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030716.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030716_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030723.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030723.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030723.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030723_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030730.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030730.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030730.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030730_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030806.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030806.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030806.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030806_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030812.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030812.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030812.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030812_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030820.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030820.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030820.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030820_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030827.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030827.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030827.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030827_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030903.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030903.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030903.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030903_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030918.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030918.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030918.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030918_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030926a.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030926a.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030926a.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030926a_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030926b.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030926b.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030926b.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/030926b_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031001.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031001.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031001.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031001_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031009.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031009.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031009.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031009_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031016.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031016.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031016.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031016_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031030.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031030.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031030.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031030_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031109.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031109.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031109.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031109_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031116.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031116.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031116.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031116_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031129.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031129.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031129.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/031129_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040005.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040005.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040005.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040005_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040014.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040014.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040014.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040014_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040028.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040028.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040028.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040028_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040104.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040104.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040104.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040104_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040111.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040111.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040111.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040111_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040118.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040118.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040118.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040118_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040128.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040128.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040128.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040128_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040201.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040201.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040201.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040201_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040209.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040209.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040209.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040209_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040216.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040216.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040216.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040216_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040223.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040223.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040223.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040223_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040228.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040228.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040228.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040228_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040307.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040307.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040307.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040307_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040313.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040313.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040313.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040313_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040319.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040319.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040319.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040319_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040326.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040326.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040326.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040326_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040401.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040401.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040401.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040401_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040411.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040411.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040411.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040411_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040418.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040418.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040418.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040418_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040425.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040425.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040425.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040425_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040504.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040504.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040504.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040504_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040508.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040508.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040508.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040508_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040514.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040514.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040514.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040514_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040522.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040522.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040522.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040522_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040529.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040529.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040529.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040529_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040605.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040605.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040605.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040605_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040610.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040610.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040610.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040610_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040617.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040617.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040617.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040617_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040624.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040624.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040624.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040624_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040700.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040700.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040700.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040700_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040711.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040711.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040711.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040711_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040717.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040717.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040717.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040717_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040724.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040724.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040724.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040724_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040807.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040807.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040807.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040807_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040813.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040813.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040813.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040813_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040820.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040820.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040820.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040820_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040904.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040904.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040904.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040904_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040912.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040912.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040912.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040912_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040919.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040919.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040919.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040919_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040926.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040926.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040926.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/040926_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041006.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041006.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041006.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041006_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041021.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041021.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041021.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041021_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041027.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041027.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041027.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041027_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041104.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041104.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041104.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041104_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041113.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041113.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041113.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041113_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041119.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041119.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041119.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041119_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041126.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041126.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041126.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/041126_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050002.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050002.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050002.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050002_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050010.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050010.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050010.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050010_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050016.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050016.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050016.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050016_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050025.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050025.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050025.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050025_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050030.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050030.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050030.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050030_ipsyn.txt
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050106.cha
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050106.ipcore.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050106.ipsyn.cex
ipsyn +o*CHI –leng /Users/lucasfedronic/Downloads/Brown_Transcripts/Sarah/050106_ipsyn.txt
