ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600a1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600a2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600a3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600a4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600a5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600a6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600a7.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600b1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600b2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600b3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600b4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600b5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010600b6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010700a1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010700a2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010700b1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010700b2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010700b3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010700b4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010700b5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010700b6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/0108001.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/0108002.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/0108003.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/0108004.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/0108005.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/0108006.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900a1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900a2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900a3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900a4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900a5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900b1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900b2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900b3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900b4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900b5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900b6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900c1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900c2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900c3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900c4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900c5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900c6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900c7.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900c8.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/010900c9.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000a1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000a2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000a3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000a4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000a5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000b1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000b2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000b3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000b4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011000b5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100a1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100a2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100a3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100a4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100b1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100b2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100b3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100b4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100b5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/011100b6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020000a1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020000a2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020000a3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020000a4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020000b1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020000b2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020000b3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020000b4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020000b5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100a1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100a2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100a3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100a4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100a5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100a6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100a7.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100b1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100b2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100b3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100b4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100b5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100b6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020100b7.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a10.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a7.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a8.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200a9.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200b1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200b2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200b3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200b4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200b5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200b6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200b7.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020200b8.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300a1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300a2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300a3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300a4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300a5.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300a6.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300b1.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300b2.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300b3.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300b4.cha
ipsyn +t*CHI +o –leng /Users/lucasfedronic/Split_Transcripts/020300b5.cha
